version: '2.1'
services:
  backend:
    build: .
    env_file:
      - ./extras_app.env
    expose:
      - "8000"
    links:
      - db:db
      - redis:redis
    volumes:
      - ./static:/code/static
      - ./media:/code/media
      - ./logs:/var/log/balance_app
    depends_on:
      - redis
      - db
    restart: unless-stopped

  celery:
    build: .
    env_file:
      - ./extras_app.env
    environment:
      - DJANGO_CONFIGURATION=Prod
    links:
      - db:db
      - redis:redis
    volumes:
      - ./static:/code/static
      - ./media:/code/media
    depends_on:
      - redis
      - db
    restart: unless-stopped
    command: bash -c "mkdir -p /var/log/balance_app && \
      touch /var/log/balance_app/app.log && sleep 30 &&  \
      /venv/bin/celery -A core worker -l INFO"

  migrations:
    build: .
    env_file:
      - ./extras_app.env
    environment:
      - DJANGO_CONFIGURATION=Prod
    command: bash -c "mkdir -p /var/log/balance_app && \
      touch /var/log/balance_app/app.log && sleep 15 && \
      /venv/bin/python manage.py makemigrations && \
      /venv/bin/python manage.py migrate --no-input"
    links:
      - db:db
      - redis:redis
    depends_on:
      - db
    restart: on-failure
    labels:
      io.rancher.container.start_once: 'true'
  
  super_user:
    build: .
    env_file:
      - ./extras_app.env
    environment:
      - DJANGO_CONFIGURATION=Prod
    command: bash -c "mkdir -p /var/log/balance_app && \
      touch /var/log/balance_app/app.log && sleep 30 && \
      /venv/bin/python manage.py makemigrations && \
      /venv/bin/python manage.py createsuperuser --no-input"
    links:
      - db:db
      - redis:redis
    depends_on:
      - db
    restart: on-failure
    labels:
      io.rancher.container.start_once: 'true'
  
  collectstatic:
    build: .
    env_file:
      - ./extras_app.env
    environment:
      - DJANGO_CONFIGURATION=Prod
    command: bash -c "mkdir -p /var/log/balance_app && \
      touch /var/log/balance_app/app.log && sleep 30 && \
      /venv/bin/python manage.py collectstatic --no-input"
    links:
      - db:db
      - redis:redis
    volumes:
      - ./static:/code/static
      - ./media:/code/media
    depends_on:
      - db
    restart: on-failure
    labels:
      io.rancher.container.start_once: 'true'

  redis:
    image: redis:latest
    restart: unless-stopped

  db:
    image: postgres:latest
    env_file:
      - ./extras_db.env
    expose:
      - "5432"
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports: 
      - "8000:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/code/static
      - ./media:/code/media
    depends_on:
      - backend
    env_file:
      - ./extras_nginx.env
    restart: unless-stopped
