version: '2.1'
services:
  backend:
    build: .
    env_file:
      - ./extras_app.env
    expose:
      - "8000"
    links:
      - db:db
      - redis:redis
    volumes:
      - ./media:/code/media
      - ./logs:/var/log/balance_app
      - ./static:/code/static
    depends_on:
      - redis
      - db
    restart: unless-stopped

  celery:
    build: .
    env_file:
      - ./extras_app.env
    links:
      - db:db
      - redis:redis
    volumes:
      - ./media:/code/media
      - ./celery_logs:/var/log/balance_app
    depends_on:
      - redis
      - db
    restart: unless-stopped
    entrypoint: /code/celery_entrypoint.sh

  redis:
    image: redis:latest
    restart: unless-stopped

  db:
    image: postgres:latest
    env_file:
      - ./extras_db.env
    expose:
      - "5432"
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports: 
      - "8000:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/code/static
      - ./media:/code/media
    depends_on:
      - backend
    env_file:
      - ./extras_nginx.env
    restart: unless-stopped
